version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
