export const users = [
  {
    id: "0",
    firstName: "John",
    lastName: "Doe",
    fullName: "John Doe",
    email: "doe.john@gmail.com",
    username: "johny",
    password: "password",
  },
  {
    id: "1",
    firstName: "Rick",
    lastName: "Sanchez",
    fullName: "Rick Sanchez",
    email: "sanchez.rick@gmail.com",
    username: "grandpa_rick",
    password: "password",
  },
  {
    id: "2",
    firstName: "Morty",
    lastName: "Smith",
    fullName: "Morty Smith",
    email: "smith.morty@gmail.com",
    username: "mortified",
    password: "password",
  },
  {
    id: "3",
    firstName: "James",
    lastName: "Segura",
    fullName: "James Segura",
    email: "segura.james@gmail.com",
    username: "ballhog",
    password: "password",
  },
  {
    id: "4",
    firstName: "TestFirstName",
    lastName: "TestLastName",
    fullName: "TestFirstName testLastName",
    email: "testlastname.testfirstname@gmail.com",
    username: "testUsername",
    password: "password",
  },
];
